# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ubc.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'ubc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tubc.proto\x12\x0f\x64ose.proto.main\x1a\x0c\x63ommon.proto\"\xff\x02\n\nUBCMessage\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.dose.proto.common.Header\x12\x0c\n\x04tick\x18\x02 \x01(\r\x12\x12\n\nsession_id\x18\x03 \x01(\r\x12\x35\n\x08payloads\x18\x04 \x03(\x0b\x32#.dose.proto.main.UBCMessage.Payload\x1a\xec\x01\n\x07Payload\x12\x11\n\tdevice_id\x18\x01 \x01(\x04\x12=\n\x0b\x64\x61ta_fields\x18\x02 \x03(\x0b\x32(.dose.proto.main.UBCMessage.Payload.Data\x1a\x8e\x01\n\x04\x44\x61ta\x12\r\n\x05\x66ield\x18\x01 \x01(\r\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x13\n\tint_value\x18\x03 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x02H\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x12\x15\n\x0b\x62ytes_value\x18\x06 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61tab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ubc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UBCMESSAGE']._serialized_start=45
  _globals['_UBCMESSAGE']._serialized_end=428
  _globals['_UBCMESSAGE_PAYLOAD']._serialized_start=192
  _globals['_UBCMESSAGE_PAYLOAD']._serialized_end=428
  _globals['_UBCMESSAGE_PAYLOAD_DATA']._serialized_start=286
  _globals['_UBCMESSAGE_PAYLOAD_DATA']._serialized_end=428
# @@protoc_insertion_point(module_scope)
