# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uec.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'uec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import server.protocols.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tuec.proto\x12\x0f\x64ose.proto.main\x1a\x0c\x63ommon.proto\"\x90\x01\n\nUECMessage\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.dose.proto.common.Header\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x11\n\ttick_hint\x18\x03 \x01(\r\x12\x12\n\nsession_id\x18\x04 \x01(\r\x12\x12\n\nevent_type\x18\x05 \x01(\r\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UECMESSAGE']._serialized_start=45
  _globals['_UECMESSAGE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
